// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace DataRecovery.Models
{
    [Table("tblDriveDetails", Schema = "dbo")]
    public partial class tblDriveDetails
    {
        [Key]
        public int DriveDetailId { get; set; }
        [StringLength(50)]
        public string SystemId { get; set; }
        [StringLength(50)]
        public string SerialNumber { get; set; }
        [Required]
        [StringLength(50)]
        public string DriveName { get; set; }
        [Required]
        [StringLength(50)]
        public string FreeSpace { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedOn { get; set; }
        [Required]
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedOn { get; set; }
        [StringLength(50)]
        public string UpdatedBy { get; set; }
        public bool IsActive { get; set; }
    }
}