// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;



namespace DataRecoveryWebService.Models
{
    [Table("tblMailUtilityConfig", Schema = "dbo")]
    public partial class tblMailUtilityConfig
    {
        [Key]
        public int MailConfigid { get; set; }
        [StringLength(50)]
        public string MailType { get; set; }
        [Required]
        public string MailServer { get; set; }
        [Required]
        public string MailBoxUserName { get; set; }
        [Required]
        public string MailBoxPassword { get; set; }
        [Required]
        [StringLength(50)]
        public string MailBoxMailId { get; set; }
        public int MailBoxPort { get; set; }
        [Required]
        [StringLength(50)]
        public string MailProtocol { get; set; }
        public int MailWindowsServiceInterval { get; set; }
        [Required]
        public bool? IsActive { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedOn { get; set; }
        [StringLength(50)]
        public string UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime UpdatedOn { get; set; }
    }
}