// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace DataRecoveryWebService.Models
{
    [Table("tblPerformanceMonitor")]
    public partial class tblPerformanceMonitor
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string SystemId { get; set; }
        [Required]
        [StringLength(50)]
        public string SerialNumber { get; set; }
        public int CpuUsagePercentage { get; set; }
        public int MemoryUsagePercentage { get; set; }
        public int HardDiskUsagePercentage { get; set; }
        public bool IsActive { get; set; }
        [Required]
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedOn { get; set; }
        [StringLength(50)]
        public string UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedOn { get; set; }
    }
}