// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Configuration;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration.Conventions;

namespace DataRecovery.Models
{
    public partial class DatarecoveryContext : DbContext
    {
      


        public DatarecoveryContext(): base(ConfigurationManager.ConnectionStrings["dbconnection"].ConnectionString)
        {
        }

        public virtual DbSet<tblBackups> tblBackups { get; set; }
        public virtual DbSet<tblConfigMaster> tblConfigMaster { get; set; }
        public virtual DbSet<tblConfigs> tblConfigs { get; set; }
        public virtual DbSet<tblDriveDetails> tblDriveDetails { get; set; }
        public virtual DbSet<tblHardwareInventories> tblHardwareInventories { get; set; }
        public virtual DbSet<tblModules> tblModules { get; set; }
        public virtual DbSet<tblSoftwareInventories> tblSoftwareInventories { get; set; }
        public virtual DbSet<tblUserMachineMappings> tblUserMachineMappings { get; set; }

        public virtual DbSet<tblConfigKeys> tblConfigKeys { get; set; }

        public virtual DbSet<tblConfigMasterKeys> tblConfigMasterKeys { get; set; }

        public virtual DbSet<tblRequests> tblRequests { get; set; }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
        }

        public System.Data.Entity.DbSet<DataRecovery.Models.ConfigsVm> ConfigsVms { get; set; }

        public System.Data.Entity.DbSet<DataRecovery.Models.ConfigMasterVm> ConfigMasterVms { get; set; }
    }
}