// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace ITManager.Common.Models
{
    public partial class tblEngineRequests
    {
        public int RequestId { get; set; }

        public string EngineName { get; set; }
        public string GroupName { get; set; }
        public string UpdateId { get; set; }
        public int? RequestStatus { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    }
}