// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ITManager.Common.Models
{
    public partial class tblEngineReports
    {
        public int ReportId { get; set; }

        public string EngineName { get; set; }

        public string SystemId { get; set; }
        
        public string UpdateId { get; set; }
        public string Status { get; set; }
        public DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }

        public DateTime? UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    }
}