// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ITManager.Common
{
    public class NotificationFieldMatrix
    {
        [Key]
        public int Id { get; set; }
        [StringLength(256)]
        public string StageName { get; set; }
        [StringLength(256)]
        public string RoleName { get; set; }
        [StringLength(256)]
        public string FieldName { get; set; }
        public bool? IsActive { get; set; }
        public bool? IsDeleted { get; set; }
        public int? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedOn { get; set; }
        public int? ChangedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ChangedOn { get; set; }
        public int? DeletedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DeletedOn { get; set; }
    }
}
