// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataRecoveryWebService.Models
{
    public partial class tblEngineUpdates
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string UpdateId { get; set; }
        [Required]
        public string Title { get; set; }

        public string EngineName { get; set; }

        [Required]
        public string Description { get; set; }
        public int? MajorVersion { get; set; }
        public int? MinorVersion { get; set; }
        public int? KB { get; set; }
        [StringLength(50)]
        public string UpdateClassificationTitle { get; set; }
        [StringLength(50)]
        public string CompanyTitle { get; set; }
        [StringLength(50)]
        public string ProductTitles { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ArrivalDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedOn { get; set; }
        [Required]
        [StringLength(50)]
        public string CreatedBy { get; set; }
    }
}