// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace DataRecoveryWebService.Models
{
    [Table("tblMailMessages", Schema = "dbo")]
    public partial class tblMailMessage
    {
        [Key]
        public int MailMessageId { get; set; }
        [Required]
        public string MailServerMessageId { get; set; }
        [Required]
        [StringLength(50)]
        public string MailProtocol { get; set; }
        [StringLength(256)]
        public string FromAddress { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ReceivedOn { get; set; }
       
        public string BodyType { get; set; }
        public bool? IsActive { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedOn { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedOn { get; set; }
        [StringLength(50)]
        public string UpdatedBy { get; set; }

        public string TicketNumber { get; set; }

    }
}