// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace DataRecoveryWebService.Models
{
    public partial class UserInformation
    {
        [Key]
        public int Id { get; set; }
        [StringLength(550)]
        public string AccountExpirationDate { get; set; }
        [StringLength(550)]
        public string accountExpires { get; set; }
        [StringLength(550)]
        public string AccountLockoutTime { get; set; }
        public bool AccountNotDelegated { get; set; }
        [StringLength(550)]
        public string AdminCount { get; set; }
        public bool AllowReversiblePasswordEncryption { get; set; }
        public string AuthenticationPolicy { get; set; }
        public string AuthenticationPolicySilo { get; set; }
        [StringLength(550)]
        public string BadLogonCount { get; set; }
        [StringLength(550)]
        public string BadPasswordTime { get; set; }
        [StringLength(550)]
        public string BadPwdCount { get; set; }
        public bool CannotChangePassword { get; set; }
        public string CanonicalName { get; set; }
        public string Certificates { get; set; }
        public string City { get; set; }
        public string CN { get; set; }
        [StringLength(550)]
        public string CodePage { get; set; }
        public string Company { get; set; }
        public string CompoundIdentitySupported { get; set; }
        public string Country { get; set; }
        public string CountryCode { get; set; }
        [StringLength(550)]
        public string Created { get; set; }
        [StringLength(550)]
        public string CreateTimeStamp { get; set; }
        public bool Deleted { get; set; }
        public string Department { get; set; }
        public string Description { get; set; }
        public string DisplayName { get; set; }
        public string DistinguishedName { get; set; }
        public string Division { get; set; }
        public bool DoesNotRequirePreAuth { get; set; }
        [StringLength(550)]
        public string dSCorePropagationData { get; set; }
        public string EmailAddress { get; set; }
        public string EmployeeID { get; set; }
        [StringLength(550)]
        public string EmployeeNumber { get; set; }
        public string Enabled { get; set; }
        public string Fax { get; set; }
        public string GivenName { get; set; }
        public string HomeDirectory { get; set; }
        public string HomedirRequired { get; set; }
        public string HomeDrive { get; set; }
        public string HomePage { get; set; }
        public string HomePhone { get; set; }
        public string Initials { get; set; }
        [StringLength(550)]
        public string instanceType { get; set; }
        public bool isDeleted { get; set; }
        public string KerberosEncryptionType { get; set; }
        public string LastKnownParent { get; set; }
        [StringLength(550)]
        public string lastLogoff { get; set; }
        public string lastLogon { get; set; }
        [StringLength(550)]
        public string LastLogonDate { get; set; }
        public string lastLogonTimestamp { get; set; }
        public bool LockedOut { get; set; }
        [StringLength(550)]
        public string LogonCount { get; set; }
        public string LogonWorkstations { get; set; }
        public string Manager { get; set; }
        public string MemberOf { get; set; }
        public bool MNSLogonAccount { get; set; }
        public string MobilePhone { get; set; }
        [StringLength(550)]
        public string Modified { get; set; }
        [StringLength(550)]
        public string modifyTimeStamp { get; set; }
        [StringLength(550)]
        public string MsdsuserAccountControlComputed { get; set; }
        public string Name { get; set; }
        public string NTSecurityDescriptor { get; set; }
        public string ObjectCategory { get; set; }
        public string ObjectClass { get; set; }
        [StringLength(550)]
        public string ObjectGUID { get; set; }
        [StringLength(550)]
        public string ObjectSid { get; set; }
        public string Office { get; set; }
        public string OfficePhone { get; set; }
        public string Organization { get; set; }
        public string OtherName { get; set; }
        public bool PasswordExpired { get; set; }
        [StringLength(550)]
        public string PasswordLastSet { get; set; }
        public bool PasswordNeverExpires { get; set; }
        public bool PasswordNotRequired { get; set; }
        public string POBox { get; set; }
        public string PostalCode { get; set; }
        public string PrimaryGroup { get; set; }
        public string PrimaryGroupID { get; set; }
        public string PrincipalsAllowedToDelegateToAccount { get; set; }
        public string ProfilePath { get; set; }
        public bool ProtectedFromAccidentalDeletion { get; set; }
        public string pwdLastSet { get; set; }
        public string SamAccountName { get; set; }
        public string Password { get; set; }
        public string SAMAccountType { get; set; }
        public string ScriptPath { get; set; }
        public string sDRightsEffective { get; set; }
        public string ServicePrincipalNames { get; set; }
        public string SID { get; set; }
        public string SIDHistory { get; set; }
        public bool SmartcardLogonRequired { get; set; }
        public string State { get; set; }
        public string StreetAddress { get; set; }
        public string Surname { get; set; }
        public string Title { get; set; }
        public bool TrustedForDelegation { get; set; }
        public bool TrustedToAuthForDelegation { get; set; }
        public bool UseDESKeyOnly { get; set; }
        public string userAccountControl { get; set; }
        public string userCertificate { get; set; }
        public string UserPrincipalName { get; set; }
        public string USNChanged { get; set; }
        public string USNCreated { get; set; }
        [StringLength(550)]
        public string whenChanged { get; set; }
        [StringLength(550)]
        public string whenCreated { get; set; }
        public string Userphoto { get; set; }
        public string Customename { get; set; }
        public string Status { get; set; }
    }
}